'use client';

import * as React from 'react';
import Link from 'next/link';
import {
  Shield,
  ArrowLeft,
  FileText,
  Search,
  CheckCircle2,
  RotateCcw,
  BarChart3,
  BookOpen,
  Lock,
  Layers,
  ChevronRight,
} from 'lucide-react';
import { ThemeToggle } from '@/components/layout/theme-toggle';
import { Button } from '@/components/ui/button';

export default function DocsPage() {
  return (
    <div className="min-h-screen bg-slate-50/70 dark:bg-[#0c1017] text-foreground flex flex-col selection:bg-muted relative">
      {/* Top Navigation */}
      <header className="sticky top-0 z-30 w-full border-b border-border/80 bg-background/80 backdrop-blur-md">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Link
              href="/projects"
              className="flex items-center gap-2 group outline-none focus-visible:ring-1 focus-visible:ring-ring rounded-md p-1"
            >
              <div className="h-6 w-6 rounded bg-foreground text-background flex items-center justify-center shrink-0 shadow-xs relative">
                <Shield className="h-3.5 w-3.5 fill-current" />
                <span className="absolute -top-0.5 -right-0.5 h-1.5 w-1.5 rounded-full bg-status-verified ring-2 ring-background" />
              </div>
              <span className="text-xs font-bold tracking-tight text-foreground">
                EvideX
              </span>
            </Link>
            <span className="text-border">/</span>
            <span className="text-xs font-medium text-muted-foreground">
              Documentation
            </span>
          </div>

          <div className="flex items-center gap-2.5">
            <ThemeToggle />
            <Button
              variant="outline"
              size="sm"
              asChild
              className="h-8 text-xs font-semibold gap-1.5 cursor-pointer"
            >
              <Link href="/projects">
                <ArrowLeft className="h-3.5 w-3.5" />
                <span>Workspaces</span>
              </Link>
            </Button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 max-w-5xl w-full mx-auto px-4 sm:px-6 py-10 space-y-12">
        {/* Intro Banner */}
        <div className="space-y-3 pb-6 border-b border-border/60">
          <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-primary/10 border border-primary/20 text-primary text-xs font-medium">
            <BookOpen className="h-3.5 w-3.5" />
            <span>Product Manual & Architectural Invariants</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-foreground">
            EVIDEX AI Reliability Platform
          </h1>
          <p className="text-sm sm:text-base text-muted-foreground max-w-2xl leading-relaxed">
            EVIDEX is an evidence-grounded AI system designed to ensure every claim generated by language models
            is auditable, verifiable, and strictly bound to source documentation.
          </p>
        </div>

        {/* 5 Core Pillars */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Pillar 1 */}
          <div className="p-5 rounded-xl border border-border/70 bg-card/60 space-y-3 shadow-xs">
            <div className="h-8 w-8 rounded-lg bg-emerald-500/10 text-emerald-500 flex items-center justify-center">
              <Lock className="h-4 w-4" />
            </div>
            <h2 className="text-sm font-semibold text-foreground">
              1. Project Isolation Boundary
            </h2>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Every workspace partitions documents, vector embeddings in Qdrant, and conversational history in PostgreSQL.
              Retrieved passages never bleed across different project workspaces.
            </p>
          </div>

          {/* Pillar 2 */}
          <div className="p-5 rounded-xl border border-border/70 bg-card/60 space-y-3 shadow-xs">
            <div className="h-8 w-8 rounded-lg bg-cyan-500/10 text-cyan-500 flex items-center justify-center">
              <Search className="h-4 w-4" />
            </div>
            <h2 className="text-sm font-semibold text-foreground">
              2. Hybrid Dense-Sparse Retrieval
            </h2>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Queries retrieve technical evidence using dense semantic vectors paired with exact lexical keyword matching.
              Retrieved passages undergo reciprocal rank fusion before generation.
            </p>
          </div>

          {/* Pillar 3 */}
          <div className="p-5 rounded-xl border border-border/70 bg-card/60 space-y-3 shadow-xs">
            <div className="h-8 w-8 rounded-lg bg-emerald-500/10 text-emerald-500 flex items-center justify-center">
              <CheckCircle2 className="h-4 w-4" />
            </div>
            <h2 className="text-sm font-semibold text-foreground">
              3. Atomic NLI Claim Verification
            </h2>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Generated answer prose is decomposed into atomic factual assertions. A cross-encoder Natural Language Inference
              (NLI) model scores entailment against cited source passages with a fixed 0.35 sufficiency invariant.
            </p>
          </div>

          {/* Pillar 4 */}
          <div className="p-5 rounded-xl border border-border/70 bg-card/60 space-y-3 shadow-xs">
            <div className="h-8 w-8 rounded-lg bg-sky-500/10 text-sky-500 flex items-center justify-center">
              <RotateCcw className="h-4 w-4" />
            </div>
            <h2 className="text-sm font-semibold text-foreground">
              4. Autonomous Recovery Rails
            </h2>
            <p className="text-xs text-muted-foreground leading-relaxed">
              If an extracted claim contradicts retrieved evidence or lacks entailment, the autonomous recovery agent performs
              secondary targeted passage retrieval and repairs the claim prior to final answer projection.
            </p>
          </div>
        </div>

        {/* Claim State Definitions */}
        <section className="space-y-4 pt-4">
          <h2 className="text-base font-semibold text-foreground">
            Canonical Claim Trust States
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3.5">
            <div className="p-3.5 rounded-lg border border-status-verified-border bg-status-verified-bg/40 space-y-1">
              <div className="text-xs font-bold text-status-verified flex items-center gap-1.5">
                <span className="h-1.5 w-1.5 rounded-full bg-status-verified" />
                <span>Verified</span>
              </div>
              <p className="text-[11px] text-muted-foreground leading-relaxed">
                Atomic claim is directly entailed by cited source passages with high confidence.
              </p>
            </div>

            <div className="p-3.5 rounded-lg border border-status-recovered-border bg-status-recovered-bg/40 space-y-1">
              <div className="text-xs font-bold text-status-recovered flex items-center gap-1.5">
                <span className="h-1.5 w-1.5 rounded-full bg-status-recovered" />
                <span>Recovered</span>
              </div>
              <p className="text-[11px] text-muted-foreground leading-relaxed">
                Initial unverified draft was autonomously corrected through secondary retrieval.
              </p>
            </div>

            <div className="p-3.5 rounded-lg border border-status-needs-review-border bg-status-needs-review-bg/40 space-y-1">
              <div className="text-xs font-bold text-status-needs-review flex items-center gap-1.5">
                <span className="h-1.5 w-1.5 rounded-full bg-status-needs-review" />
                <span>Needs Review</span>
              </div>
              <p className="text-[11px] text-muted-foreground leading-relaxed">
                Evidence is insufficient or neutral; flagged for human expert verification.
              </p>
            </div>

            <div className="p-3.5 rounded-lg border border-status-flagged-border bg-status-flagged-bg/40 space-y-1">
              <div className="text-xs font-bold text-status-flagged flex items-center gap-1.5">
                <span className="h-1.5 w-1.5 rounded-full bg-status-flagged" />
                <span>Flagged</span>
              </div>
              <p className="text-[11px] text-muted-foreground leading-relaxed">
                Contradicts source text or fails strict factual grounding threshold.
              </p>
            </div>
          </div>
        </section>

        {/* Footer Navigation */}
        <div className="pt-6 border-t border-border/60 flex items-center justify-between text-xs text-muted-foreground">
          <span>EVIDEX Documentation · Platform Architecture v1.0</span>
          <Link href="/projects" className="text-primary hover:underline font-medium flex items-center gap-1">
            <span>Open Workspaces</span>
            <ChevronRight className="h-3 w-3" />
          </Link>
        </div>
      </main>
    </div>
  );
}
