FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json* ./
COPY packages ./packages
COPY apps/web ./apps/web

RUN npm install
RUN npm --prefix packages/types run build
RUN npm --prefix apps/web run build

EXPOSE 3000

CMD ["npm", "--prefix", "apps/web", "run", "start"]
